produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.index, name='index'),
    path('lista_produtos/', views.lista_produtos, name='lista_produtos'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('atualiza_produtos/', views.atualiza_produtos, name='atualiza_produtos'),
    path('deleta_produto/', views.deleta_produto, name='deleta_produto'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from projeto import views

urlpatterns = [
    path('', include('produto.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
]

#     Como acessar a página index.html do projeto:
#     http://127.0.0.1:8000/
#
#     Como acessar a página index.html de produto:
#     http://127.0.0.1:8000/produto/

categoria/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=70, db_index=True, unique=True)
    slug = models.SlugField(max_length=70)

    class Meta:
        db_table='categoria'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

produto/models.py
from decimal import Decimal

from django.db import models
from categoria.models import Categoria
from projeto import settings


class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=100)
    qtd = models.IntegerField()
    preco = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        db_table='produto'

    def __str__(self):
        return self.nome

produto/forms.py
from django import forms

from categoria.models import Categoria
from produto.models import Produto


class QuantidadeForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    qtd = forms.IntegerField(widget=forms.TextInput())


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = ('nome', 'categoria', 'preco', 'qtd')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].queryset = Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label = '--- Selecione uma categoria ---'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['preco'].min_value = 0
        self.fields['preco'].error_messages = {'invalid': 'Valor inválido.',
                                               'max_digits': 'Mais de 5 dígitos no total.',
                                               'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                               'max_whole_digits': 'Mais de 3 dígitos inteiros.'}
        self.fields['preco'].widget.attrs.update({
            'class': 'form-control form-control-sm'
        })

        self.fields['qtd'].min_value=1
        self.fields['qtd'].error_messages={
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['qtd'].widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

categoria/views.py
from django.shortcuts import render

# Create your views here.

produto/views.py
import locale
from decimal import Decimal

from django.db.models import Sum, F
from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from produto.forms import ProdutoForm, QuantidadeForm
from produto.models import Produto


def index(request):
    return render(request, 'produto/index.html')


def lista_produtos(request):
    lista_de_produtos = Produto.objects.all()
    preco_total = Decimal("0")
    lista_de_forms = []

    for produto in lista_de_produtos:
        preco_total += (produto.qtd * produto.preco)

        lista_de_forms.append(QuantidadeForm(initial={
            'qtd': produto.qtd,
            'id': produto.id
        }))

    locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
    preco = locale.currency(preco_total, grouping=True)

    context = {
        'listas': zip(lista_de_produtos, lista_de_forms),
        'valor_total': preco
    }

    return render(request, 'produto/lista_produtos.html', context=context)


@csrf_exempt
def atualiza_produtos(request):
    form = QuantidadeForm(request.POST)

    if form.is_valid():
        id = form.cleaned_data['id']
        qtd = form.cleaned_data['qtd']

        produto = get_object_or_404(Produto, pk=id)
        produto.qtd = qtd
        produto.save()

        resultado = Produto.objects.aggregate(preco_total=Sum(F('preco') * F('qtd')))
        preco_total = Decimal(resultado['preco_total'])

        locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
        preco = locale.currency(preco_total, grouping=True)

        return JsonResponse({'preco_total': preco})

    else:
        raise ValueError('Error')


@csrf_exempt
def deleta_produto(request):
    form = QuantidadeForm(request.POST)
    id = form.data['id']

    produto = get_object_or_404(Produto, pk=id)
    produto.delete()

    resultado = Produto.objects.aggregate(preco_total=Sum(F('preco') * F('qtd')))
    preco_total = Decimal(resultado['preco_total'])

    locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
    preco = locale.currency(preco_total, grouping=True)

    return JsonResponse({'preco_total': preco})


@csrf_exempt
def cadastra_produto(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.POST:
        produto_form = ProdutoForm(request.POST)

        if produto_form.is_valid():
            locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

            produto = produto_form.save(commit=False)
            produto.preco = Decimal(produto.preco).quantize(Decimal("0.01"))
            produto.save()

            resultado = Produto.objects.aggregate(preco_total=Sum(F('preco') * F('qtd')))
            preco_total = Decimal(resultado['preco_total'])

            preco = locale.currency(preco_total, grouping=True)

            novo_produto = model_to_dict(produto)
            novo_produto["preco"] = locale.currency(produto.preco, grouping=True)

            return JsonResponse({'novoProduto': novo_produto,
                                 'categoria': model_to_dict(produto.categoria),
                                 'preco_total': preco}, safe=False)
    else:
        produto_form = ProdutoForm()

    context = {
        'form': produto_form
    }
    return render(request, 'produto/cadastra_produto.html', context=context)

projeto/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

produto/templates/produto/cadastra_produto.html
{% load static %}

{% block corpo %}
   <form onkeydown="return event.key != 'Enter';" action="{% url 'produto:cadastra_produto' %}" method="POST" class="pb-4" novalidate>
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.nome }}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.categoria }}
                  {% comment %}
                     <select name="categoria" required="" id="id_categoria">
                        <option value="" selected="">---------</option>
                        <option value="1">Frutas</option>
                        <option value="2">Legumes</option>
                        <option value="3">Verduras</option>
                     </select>
                  {% endcomment %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_preco" class="col-xl-2 font-weight-bold">Preço</label>
               <div class="col-xl-10">
                  {{ form.preco }}
               </div>
            </div>
         </div>
               </div>
       <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_qtd" class="col-xl-2 font-weight-bold">Quantidade</label>
               <div class="col-xl-10">
                  {{ form.qtd }}
               </div>
            </div>
         </div>
      </div>

      <br>
      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  <button id="botao" type="button" class="btn btn-primary adicionar">
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>

{% endblock %}

produto/templates/produto/index.html
{% extends "base.html" %}


{% block titulo %}
    Venda de produtos
{% endblock %}

{% block estilo %}

{% endblock %}

{% block corpo %}
    <br>

    <div id="form">

    </div>
    <br>
    <div id="tabela">

    </div>
    <br>
    <br>
    <br>
{% endblock %}

{% block domready %}
    $.get("{% url 'produto:cadastra_produto' %}", function (resposta) {
        $("#form").html(resposta)
    })

    $.get("{% url 'produto:lista_produtos' %}", function (resposta) {
        $("#tabela").html(resposta)
    })

<!--    Atualiza com método ajax a tabela, com o novo preco total-->
    $("#tabela").on("blur", "input", function() {
        let valor = $(this).val()
        if(valor < 1 || valor > 99) {
            $(this).focus()
            return
        }
        let form = $(this).parent()
        let url = form.attr("action")
        let formData = form.serializeArray()
        $.post(url, formData, function(resposta) {
            $(".preco-total").text(resposta.preco_total)
        })
    })

    $("#tabela").on("click", ".remover", function() {
        let form = $(this).parent()
        let url = form.attr("action")
        let tr = form.parent().parent()
        let formData = form.serializeArray()
        $.post(url, formData, function(resposta){
            tr.fadeTo('slow', 0.3, function() {
                $(this).remove()
                $(".preco-total").text(resposta.preco_total)
            })
        })
    })

    $("#form").on("click", ".adicionar", function() {
        let form = $("#form").children()
        let tr = form.parent().parent()
        let url = form.attr("action")
        let formData = form.serializeArray()
        $.post(url, formData, function(resposta){
            $(".preco-total").text(resposta.preco_total)
            $(`
                <tr>
                     <td class="text-center align-middle">
                        ${ resposta.categoria.nome }
                     </td>
                     <td class="align-middle">
                           ${ resposta.novoProduto.nome }
                     </td>
                     <td class="text-right align-middle pr-3">
                        <form class="mx-auto" onkeydown="return event.key != 'Enter';" style="width: auto" action="{% url 'produto:atualiza_produtos' %}" method="POST" novalidate>
                            <input type="hidden" value=${ resposta.novoProduto.id } name="id"/>
                            <input type="text" value=${ resposta.novoProduto.qtd } name="qtd"/>
                        </form>
                     </td>
                     <td class="text-right align-middle pr-3">
                        ${ resposta.novoProduto.preco }
                     </td>
                     <td class="text-right align-middle pr-3">
                        <form onkeydown="return event.key != 'Enter';" action="{% url 'produto:deleta_produto' %}" method="POST" novalidate>
                            <input type="hidden" value=${ resposta.novoProduto.id } name="id" />
                           <button type="button" class="btn btn-sm btn-danger remover" tabindex="-1">Remover</button>
                        </form>
                     </td>
                  </tr>
            `).insertBefore($("#ultimoTr"))
        })
    })

{% endblock %}

produto/templates/produto/lista_produtos.html
{% load static %}

{% block corpo %}

   <!-- <div style="min-height: 212px"> -->
      {% if listas %}
         <h5 class="mb-3">Lista de Produtos</h5>
         <table style='width:100%'
                class='table table-striped table-sm table-bordered table-responsive mb-4'>
            <thead>
               <tr>
                  <th class='text-center'>Categoria</th>
                  <th class='text-center'>Nome</th>
                  <th class="text-center">Quantidade</th>
                  <th class="text-center">Preço</th>
                  <th class="text-center">Operação</th>
               </tr>
            </thead>
            <tbody>
               {% for item, form in listas %}
                  <tr>
                     <td width="10%" class="text-center align-middle">
                        {{ item.categoria }}
                     </td>
                     <td width="35%" class="align-middle">
                           {{ item.nome }}
                     </td>
                     <td width="10%" class="text-right align-middle pr-3">
                        <form class="mx-auto" onkeydown="return event.key != 'Enter';" style="width: auto" action="{% url 'produto:atualiza_produtos' %}" method="POST" novalidate>
                           {{ form.id }}
                           {{ form.qtd }}
                        </form>
                     </td>
                     <td width="15%" class="text-right align-middle pr-3">
                        R$ {{ item.preco }}
                     </td>
                     <td width="15%" class="text-right align-middle pr-3">
                        <form onkeydown="return event.key != 'Enter';" action="{% url 'produto:deleta_produto' %}" method="POST" novalidate>
                           {{ form.id }}
                           <button type="button" class="btn btn-sm btn-danger remover" tabindex="-1">Remover</button>
                        </form>
                     </td>
                  </tr>
               {% endfor %}
               <tr id="ultimoTr">
                  <td colspan="3">
                     <strong style="margin-left: 10px">Valor total: </strong>
                  </td>
                  <td class="text-right pr-5">
                     <strong class="preco-total">{{ valor_total }}</strong>
                  </td>
                  <td></td>
               </tr>
            </tbody>
         </table>

      {% endif %}
   <!-- </div> -->

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title>{% block titulo %}Hortifruti{% endblock %}</title>
    <style>
        {% block estilo %}

        {% endblock %}
    </style>
</head>
<body class="barra">

    <div class="container mt-3 mb-2">
        <div class="row">
            <div class="col-3">
                <a class="d-none d-md-block" style="text-decoration: none; font-size: 16px" href="#">
                    <img src="{% static 'images/hortifruti-icon.png' %}" style="width: 70px" alt="Hortifruti">
                    Hortifruti
                </a>
                <a class="d-block d-md-none" style="text-decoration: none; font-size: 16px" href="#">
                    <img src="{% static 'images/hortifruti-icon.png' %}" style="width: 70px" alt="Hortifruti">
                </a>
            </div>
            <div class="col-6 d-flex align-items-center justify-content-center">
                <div class="d-none d-lg-block">
                    <div class="d-flex justify-content-center">
                        Já é cadastrado? Faça seu<a style="text-decoration: none" class="pl-1" href="#">login!</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Cadastre-se aqui.</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none; margin-right: 100px" href="#">Cadastrar Produto</a>
                        <a style="text-decoration: none" href="#">Listar Produtos</a>
                    </div>
                </div>
                <div class="d-block d-lg-none">
                    <div class="d-flex justify-content-center">
                        Já é cadastrado?
                    </div>
                    <div class="d-flex justify-content-center">
                        Faça seu<a style="text-decoration: none" class="pl-1" href="#">login!</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Cadastre-se aqui.</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Cadastrar Produto</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Listar Produtos</a>
                    </div>
                </div>
            </div>
            <div class="col-3 d-flex justify-content-end align-items-center">
                <div class="d-none d-sm-block">
                    <a style="text-decoration: none" href="#">
                        <img src="{% static 'images/carrinho.png' %}" style="width: 35px" alt="Carrinho">
                        Carrinho
                    </a>
                </div>
                <div class="d-block d-sm-none">
                    <a style="text-decoration: none" href="#">
                        <img src="{% static 'images/carrinho.png' %}" style="width: 35px" alt="Carrinho">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div style="padding: 3px" class="bg-danger mb-3"></div>

    <div id="container" class="container">
        {% block corpo %}

        {% endblock %}
    </div>

    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script>

        $(document).ready(function(){

            {% block domready %}

            {% endblock %}
        });
    </script>

    {% block rodape %}
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <h6>Institucional</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Política de pagamento</a></li>
                            <li><a style="text-decoration: none" href="#">Política de troca</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>Atendimento</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Fale conosco</a></li>
                            <li><a style="text-decoration: none" href="#">Prazo de entrega</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>Nossa Empresa</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Quem somos</a></li>
                            <li><a style="text-decoration: none" href="#">FAQ</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>News Letter</h6>
                        <form class="form-inline" onkeydown="return event.key != 'Enter';">
                            <label class="sr-only" for="email">Email</label>
                            <input type="text" name="email" id="email"
                                   class="form-control form-control-sm mr-2 mb-2"
                                   placeholder="Seu email">
                            <button type="submit" class="btn btn-sm btn-primary mb-2">Enviar</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block corpo %}

{% endblock %}